---
title: "2_spatial_join_mapping"
author: "YHS"
date: '2024-09-21'
output: html_document
---

```{r}
library(sf)
library(dplyr)

install.packages("mapsf")
library(mapsf) # it's a package for mapping

rm(list = ls())
```

## import all layers
```{r}

nhoods <- st_read("data/sf_layers.gpkg", layer = "neighborhoods", quiet = TRUE)
bnbs <- st_read("data/sf_layers.gpkg", layer = "airbnbs", quiet = TRUE)

```

## mapping gentrification using typology map
```{r}

head(nhoods, 5)

## measuring gentrification

nhoods <- nhoods %>%
  mutate(gentable = 1 if minc < median(minc), else 0)
  

mf_map(
  x = nhoods,
  var="gentcat",
  type = "typo",
  pal = c("pink", "red", "grey", "black"),
  lwd = .7,
  leg_title = "gent cat"
)
mf_title("Statut administratif des communes")

```

## mapping
```{r}

# Neighborhoods (polygones)
mf_map(x = nhoods, border = "white")

# Airbnbs (points)
mf_map(x = bnbs, pch = 20, cex = .3, col = "darkred", add = TRUE)

# Map title
mf_title(txt = "Airbnbs in San Francisco (2019)")


```


## Spatial join
```{r}

# how many airbnbs does a neighborhood have?
nh_joined <- st_join(x = bnbs,
                     y = nhoods,
                     join = st_contains # does x(sfnh/polygon) contains y(sfbnb/point)?
                     )

# which neighborhood is this airbnb located?
airbnb_joined <- st_join(x = bnbs,
                         y = nhoods,
                         join = st_within)

```

