# From People to Built Environment

So far, we have focused on embedding demographic data into places. However, sociologists' inquiries go beyond people to institutions. People don't just exist in places but they interact with the built environment, including local businesses, public institutions like schools, libraries, and museums, green areas like parks and trees, infrastructures like roads and bridges. In this tutorial, we will explore 1) local businesses and 2) Airbnbs.

## Geocoding

## Spatial join

1. is it qualitative or quantitative (average make sense?)
  1.1 if qualitative, use different colors or shapes (nominal or ordinal variables) --> typology map
    e.g., gentrifying vs. non-gentrifying tracts
2. does the sum make sense?
  2.1 absolute - size (e.g., total population, total number of museums) --> proportional symbol
  2.2. relative - color gradiation (e.g., % white; diversity index/segregation index) --> chorolpeth map


## Mapping businesses
```{r}
```


# Explore further: Other types of spatial data

1. Mobility data
2. Crime rates
3. Voting behaviors

